export { default as setRef } from './set-ref'
export { default as canUseDOM } from './can-use-dom'
export { default as getOwnerDocument } from './get-owner-document'
export { default as hasWindow } from './has-window'
export { default as isIosDevice } from './is-ios'
export { default as noop } from './noop'
